Updated project, source, and tests to Swift 3.0
lsunsi/ReduxSwift pull request #2
Opened 2016-09-19 01:18 UTC by regynald

Updated cartfile to use 3.0 versions for both Quick & Nimble.
Had to remove typealias Middleware since Swift 3.0 doesn't allow @escaping in type aliases

2016-09-19 01:20 UTC, regynald commented
Escaping change is [here](https://github.com/apple/swift/pull/4388/files)

2016-09-19 13:35 UTC, lsunsi commented on Cartfile.private
> +github "Quick/Nimble" "master"
this is fine for develop, but for a official master release we should probably wait until proper swift 3 support is released on both os this packages

2016-09-19 13:37 UTC, lsunsi commented on ReduxSwift.playground/Contents.swift
> +
trailing whitespace. please use swiftlint (config file is included in the project) so we can maintain a coherent code style in the project. ps: this also applied for other styling changes

2016-09-19 13:42 UTC, lsunsi commented on Sources/Core.swift
> +
I don't get this comment. Seems to me it could just be removed.

2016-09-19 13:47 UTC, lsunsi commented on Sources/Subscriptions.swift
> +open class Subscriptions<State, Key: Hashable> {
maybe this class should be public and not open. what do you think?
my reasoning about this is that this class (and member) aren't intended for subclassing

2016-09-19 13:53 UTC, lsunsi requested changes
General comments on code style and some questions. Also, please merge on develop and not on master, so I can wait on Quick/Nimble next releases and properly tag ReduxSwift releases

2016-09-25 23:21 UTC, regynald commented on Sources/Subscriptions.swift
> +open class Subscriptions<State, Key: Hashable> {
Yeah, I'm just gonna make the subscription class and associated functions public.

2016-09-30 17:12 UTC, lsunsi approved these changes

2016-09-30 17:13 UTC, merged